- name: mongodb-component
  hosts: mongodb
  become: 'yes'
  tasks:
    - name: copy file /mongo.repo to /etc/yum.repos.d/mongo.repo
      ansible.builtin.copy:
        src: /mongo.repo
        dest: /etc/yum.repos.d/mongo.repo
    - name: install mongodb-org
      ansible.builtin.yum:
        name: mongodb-org
        state: installed
    - name: start mongod
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: 'yes'
    - name: remote connections to mongodb
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: 127.0.0.1
        replace: 0.0.0.0
    - name: restart mongod
      ansible.builtin.yum:
        name: mongod
        state: restarted
