- name: redis-component
  hosts: redis
  become: yes
  tasks:
  - name: Redis is offering the repo file as a rpm
    ansible.builtin.yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: installed
  - name: Enable Redis 6.2 from package streams
    ansible.builtin.command: yum module enable redis:remi-6.2 -y
  - name: install redis
    ansible.builtin.yum:
      name: redis
      state: installed
  - name: remote connections to redis
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  - name: start redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes  